---
title: "Metoda reprezentacyjna - projekt"
author: "Łukasz Wawrowski"
date: ""
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
    css: style.css
---

# Zasady oceny

Na podstawie studium przypadku przeprowadź obliczenia oraz przygotuj raport w formie dokumentu lub prezentacji. W ocenie pod uwagę brane są poniższe kryteria: 

- Projekt zawiera wizualizacje danych: 0-4 pkt

- Wykorzystanie innych źródeł danych (raporty, dane GUS, inne badania): 0-5 pkt

- Adekwatność wykorzystanych metod: 0-5 pkt

- Jakość prezentacji/raportu (tabele zamiast zrzutów ekranu, dobór kolorów, itp.): 0-4 pkt

- Jakość kodu (komentarze, odpowiednie nazwy obiektów): 0-2 pkt 

# 1. Polski Generalny Sondaż Społeczny

Polski Generalny Sondaż Społeczny obejmuje badanie indywidualnych postaw, cenionych wartości, orientacji i zachowań społecznych, jak również pomiar zróżnicowania społeczno-demograficznego, zawodowego, edukacyjnego i ekonomicznego reprezentatywnych grup i warstw społecznych w Polsce.

Na podstawie zbioru [PGSS 2010](data/pgss2010.RData) wybierz conajmniej trzy cechy, które zawierają braki danych (max. 30%). Dla wybranych cech dokonaj estymacji dla kilku wybranych przekrojów społeczno-ekonomicznych (grupy wieku, wykształcenie, itp.) lub terytorialnych (województwa, klasa miejscowości zamieszkania, itp.). Przed estymacją zastosuj jedną z metod radzenia sobie z brakami danych.

W PGSS zmienna _weight_ zawiera tzw. wagę analityczną, która sumuje się do liczebności próby. Wyznaczenie wagi z próby jest możliwe poprzez zastosowanie następującego wzoru:

$$w=\frac{w_a}{n}\cdot N$$

gdzie:

- $w_a$ - waga analityczna
- $n$ - liczebność próby
- $N$ - liczebność populacji

Liczebność populacji Polski w 2010 roku można znaleźć m.in. w Banku Danych Lokalnych. Będzie miało to znaczenie przy szacowaniu wartości globalnych. W zbiorze PGSS nie ma informacji o warstwach i jednostkach losowania pierwszego stopnia, dlatego w deklaracji schematu losowania podajemy tylko id respondenta oraz wagę. 

Otrzymane wyniki porównaj z aktualnymi lub archiwalnymi badaniami społecznymi prowadzonymi przez GUS lub niezależne ośrodki (np. Diagnoza Społeczna).

# 2. Academic Performance Index

Dla zbioru `apipop` zaproponuj schemat losowania, który uwzględni typ szkoły oraz populację hrabstwa (zmienna _cname_). Dane o populacji hrabstw są dostępne w internecie. Można dokonać grupowania hrabstw, tak aby nowoutworzone warstwy miały porównywalną liczebność populacji. Rozmiar próby dobierz tak, aby względne błędy oszacowań średniej wartości zmiennej _api99_ w ramach hrabstw nie przekraczały 5%. Z drugiej strony nie interesuje nas próba nieznacznie mniejsza od populacji - szukamy najmniejszej próby, która spełni to założenie. Następnie sprawdź czy na podstawie wylosowanej próby wyniki dla zmiennej _api00_ będą charakteryzowały się porównywalną efektywnością.

# 3. PISA

https://www.oecd.org/pisa/data/2018database/

https://pisa.ibe.edu.pl/

# 4. ESS

Na podstawie zbioru danych z [European Social Survey ](https://www.europeansocialsurvey.org/data/country.html?c=poland) przeprowadź estymację 4 wybranych cech. W przypadku pojawienia się braków danych przeprowadź imputację. 

https://cimentadaj.github.io/blog/2019-11-15-release-essurvey/essurvey-release/