---
title: "Metoda reprezentacyjna"
author: "Łukasz Wawrowski"
date: "Case studies"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    theme: lumen
---

# Polski Generalny Sondaż Społeczny

Polski Generalny Sondaż Społeczny obejmuje badanie indywidualnych postaw, cenionych wartości, orientacji i zachowań społecznych, jak również pomiar zróżnicowania społeczno-demograficznego, zawodowego, edukacyjnego i ekonomicznego reprezentatywnych grup i warstw społecznych w Polsce.

Na podstawie zbioru [PGSS 2010](data/pgss2010.RData) wybierz conajmniej trzy cechy, które zawierają braki danych (max. 30%). Dla wybranych cech dokonaj estymacji dla kilku wybranych przekrojów społeczno-ekonomicznych (grupy wieku, wykształcenie, itp.) lub terytorialnych (województwa, klasa miejscowości zamieszkania, itp.). Przed estymacją zastosuj jedną z metod radzenia sobie z brakami danych.

W PGSS zmienna _weight_ zawiera tzw. wagę analityczną, która sumuje się do liczebności próby. Wyznaczenie wagi z próby jest możliwe poprzez zastosowanie następującego wzoru:

$$w=\frac{w_a}{n}\cdot N$$

gdzie:

- $w_a$ - waga analityczna
- $n$ - liczebność próby
- $N$ - liczebność populacji

Liczebność populacji Polski w 2010 roku można znaleźć m.in. w Banku Danych Lokalnych. Będzie miało to znaczenie przy szacowaniu wartości globalnych. W zbiorze PGSS nie ma informacji o warstwach i jednostkach losowania pierwszego stopnia, dlatego w deklaracji schematu losowania podajemy tylko id respondenta oraz wagę. 

Otrzymane wyniki porównaj z aktualnymi lub archiwalnymi badaniami społecznymi prowadzonymi przez GUS lub niezależne ośrodki (np. Diagnoza Społeczna).
