---
title: "Metoda reprezentacyjna"
subtitle: "Organizacja zajęć"
author: "&copy; Łukasz Wawrowski"
date: ""
output:
  xaringan::moon_reader:
    css: ["default.css", "default-fonts.css"]
    lib_dir: libs
    nature:
      ratio: "4:3"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Prowadzący

__dr Łukasz Wawrowski__  
lukasz.wawrowski@ue.poznan.pl

Konsultacje 

- poniedziałki: 14:00-14:45
- wtorki: 8:00-8:45

Pokój 405C

http://statystyka.ue.poznan.pl

---

# Plan zajęć

1. Wprowadzenie do metody reprezentacyjnej
2. Wprowadzenie do środowiska R
3. Proste schematy losowania
4. Złożone schematy losowania
5. Estymacja wartości globalnej
6. Estymacja wartości średniej i wskaźnika
7. Bootstrap
8. Kalibracja
9. Imputacja
10. Modelowanie danych
11. Modelowanie danych
12. Analiza danych jakościowych 
13. Analiza danych ilościowych
14. Projekt
15. Projekt

---

# Zaliczenie przedmiotu

1. Projekt zaliczeniowy realizowany podczas zajęć (20 punktów)

  - kilka zbiórów danych i zagadnień do wyboru

  - praca grupowa (4 osoby)

2. Quiz (2 x 10 punktów)

  - pytania teoretyczne i obliczeniowe

  - można korzystać z dowolnych źródeł

  - praca indywidualna

---

# Skala ocen

|  %  | ocena |
|:---:|:-----:|
|0-59 | ndst  |
|60-69| dst   |
|70-74| dst+  |
|75-84| db    |
|85-89| db+   |
|90-100| bdb   |

---

# Narzędzia

R (https://www.r-project.org/) oraz RStudio (https://www.rstudio.com/)

- lokalna wersja programu

- https://rstudio.cloud/

---

# Nieobecności

§ 27 pkt. 6 regulaminu studiów UEP

Student jest zobowiązany usprawiedliwić nieobecność na zajęciach obowiązkowych
u prowadzącego __w ciągu 7 dni roboczych__ od daty nieobecności. Usprawiedliwienia
nieobecności dokonuje się w formie pisemnej, załączając kserokopię dokumentu
poświadczającego niemożność uczestniczenia w zajęciach. Usprawiedliwienia
nieobecności można dokonać również w formie elektronicznej, poprzez przesłanie na
adres e-mail prowadzącego zajęcia skanu dokumentu poświadczającego niemożność
stawiennictwa na zajęciach. Prowadzący zajęcia ma prawo żądać od studenta
przedłożenia oryginału dokumentu potwierdzającego obiektywną przyczynę
nieobecności, przy czym dokumentem takim może być jedynie zaświadczenie lekarskie
o niezdolności do nauki albo inne urzędowe zaświadczenie (w tym zaświadczenie
wydane przez rektora albo właściwego dyrektora studiów), stwierdzające wystąpienie
zdarzenia uniemożliwiającego obecność. 

---

# Nieobecności

Dozwolone są dwie nieusprawiedliwione nieobecności.

Obniżenie oceny o 2 punkty za każdą nieobecność.

---

# Frekwencja

Na moodle znajduje się zasób o nazwie _Frekwencja_

Na początku każdych zajęć należy wybrać status _Obecność_

W przypadku braku akcji zostanie przypisany status _Nieobecność_

---

# Moodle

Metoda reprezentacyjna - stacj. II st. - (lab.) - dr Łukasz Wawrowski

---

class: center, middle, inverse

# Pytania?