---
title: "Organizacja zajęć"
author: "Łukasz Wawrowski"
date: "1-10-2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

# Prowadzący

__dr Łukasz Wawrowski__  
lukasz.wawrowski@ue.poznan.pl

Konsultacje - poniedziałki:  

- 11:15-12:00
- 18:15-19:00  

Pokój 405C

---

# Plan zajęć

1. Wprowadzenie do metody reprezentacyjnej
2. Projektowanie badania
3. Próba losowa
4. Losowanie proste
5. Losowanie złożone
6. Kalibracja
7. _
8. Imputacja
9. Analiza danych jakościowych
10. Analiza danych jakościowych
11. Analiza danych ilościowych
12. Analiza danych ilościowych
13. Modelowanie danych
14. Modelowanie danych
15. _

---

# Zaliczenie przedmiotu

Dwa projekty prezentowane podczas zajęć:

- 5.11.2018 r.
- 21.01.2018 r.

---

# Narzędzia

R (https://www.r-project.org/) oraz RStudio (https://www.rstudio.com/)

- lokalna wersja programu
- https://rstudio.cloud/

---

# Nieobecności

§ 27 pkt. 5 regulaminu studiów UEP

Student jest obowiązany usprawiedliwić nieobecność na zajęciach obowiązkowych u
prowadzącego __w ciągu 7 dni roboczych__ od daty nieobecności. Usprawiedliwienia
nieobecności dokonuje się w formie pisemnej, załączając kserokopię dokumentu
poświadczającego niemożność uczestniczenia w zajęciach. Usprawiedliwienia 
nieobecności można dokonać również w formie elektronicznej, poprzez przesłanie na
adres e-mail prowadzącego zajęcia skanu dokumentu poświadczającego niemożność
stawiennictwa na zajęciach. Prowadzący zajęcia ma prawo żądać od studenta
przedłożenia oryginału dokumentu potwierdzającego obiektywną przyczynę
nieobecności, przy czym dokumentem takim może być jedynie zaświadczenie lekarskie o
niezdolności do nauki albo inne urzędowe zaświadczenie, stwierdzające wystąpienie
zdarzenia uniemożliwiającego obecność. 

---

# Moodle

Metoda reprezentacyjna - stacj. II st. - (lab.) - dr Łukasz Wawrowski

---

class: center, middle, inverse

# Pytania?